name: lab4
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8    # Python version 3.8
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics 
    - jupyter       # Interactive notebooks
    - rioxarray     # Read/write gridded data
